OPENIG-821 Fix Sonar 'Catch Exception instead of Throwable' errors
We've been catching `Throwable instead of Exception because of potential
`NoClassDefFoundError` (low level equivalent to `ClassNotFoundException`)
to be thrown. But there is no real strong justification to catch everything.